result folder = output/results_complex_c2_100_CG2_dense_jh
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    infile.read(mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "./mesh/mesh_dense_jh_tetra.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 4
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    infile.read(mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "./mesh/mesh_dense_jh_tetra.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 1
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    infile.read(mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "./mesh/mesh_dense_jh_tetra.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 2
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    infile.read(mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "./mesh/mesh_dense_jh_tetra.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    infile.read(mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "./mesh/mesh_dense_jh_tetra.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 5
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    infile.read(mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "./mesh/mesh_dense_jh_tetra.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 3
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[42159,1],0]
  Exit code:    1
--------------------------------------------------------------------------
result folder = output/results_complex_c2_100_CG2_dense_js
Total number of elements = 23761
n = 1
Process 0: Solving nonlinear variational problem.
Process 3: Solving nonlinear variational problem.
Process 5: Solving nonlinear variational problem.
Process 1: Solving nonlinear variational problem.
Process 2: Solving nonlinear variational problem.
Process 4: Solving nonlinear variational problem.
  Process 0: Newton iteration 0: r (abs) = 3.808e+00 (tol = 1.000e-10) r (rel) = 1.000e+00 (tol = 1.000e-09)
  Process 0: Newton iteration 1: r (abs) = 9.920e-03 (tol = 1.000e-10) r (rel) = 2.605e-03 (tol = 1.000e-09)
  Process 0: Newton iteration 2: r (abs) = 1.110e-03 (tol = 1.000e-10) r (rel) = 2.915e-04 (tol = 1.000e-09)
  Process 0: Newton iteration 3: r (abs) = 1.726e-05 (tol = 1.000e-10) r (rel) = 4.533e-06 (tol = 1.000e-09)
  Process 0: Newton iteration 4: r (abs) = 1.247e-08 (tol = 1.000e-10) r (rel) = 3.274e-09 (tol = 1.000e-09)
  Process 0: Newton iteration 5: r (abs) = 7.259e-15 (tol = 1.000e-10) r (rel) = 1.906e-15 (tol = 1.000e-09)
  Process 0: Newton solver finished in 5 iterations and 5 linear solver iterations.
>> Checking out
Time elapsed = 438.0s
Done
